### ISSUE TITLE
Guard not running after a file change

### ISSUE THREAD

**Issue by dfischer** [guard/guard#357]
I installed rb-fsevent and after I change a spec the suite isn't running.

The only way to trigger it is to hit enter.

My prompt looks like this:

```
[2] guard(main)> 
```

Which is unique for this project. I haven't noticed this before. Any tips to investigate issue?

**Comment by giedriusr** [comment]
Same thing here..

```
Using guard 2.14.0
Using guard-rspec 4.7.1
```

It works on first attempt and then nothing happens when the file is modified again.

**Comment by e2** [comment]
@giedriusr - open an new issue, because too much has changed since. Especially on the debugging side.

Check out the Troubleshooting section here to help pinpoint the problem: https://github.com/guard/guard/wiki/Understanding-Guard#debugging

If nothing else, the MINIMUM I need to help you is output from this: https://github.com/guard/guard/wiki/Understanding-Guard#nope-watched-dirs-are-fine-and-i-still-dont-see-any-changes

**Comment by e2** [comment]
# NOTE: IF YOU STILL HAVE ISSUES:

Open a NEW issue here: https://github.com/guard/guard/issues/new and provide as MUCH debugging output as you can. See:

https://github.com/guard/guard/wiki/Understanding-Guard

While you're waiting, go through the above troubleshooting page on the wiki. If it's unclear somewhere or it plain sucks, just open a new issue for that and let me know I've screwed up or obfuscated something.

The first thing I WOULD try is: upgrade all related gem to their latest versions, e.g.:
```
$ gem update listen guard rb-inotify rb-fsevent
```

And make sure those versions are used in your project. You can even make sure by running `gem cleanup`.

I'm locking this thread simply to encourage opening new issues, since they're guaranteed to be unrelated. Every latest version of Guard is expected to either work flawlessly or show a useful error/warning message.

If you're having issue, I want to know. And I want to know the details too, so if it's a bug, I can fix-and-release quickly.
