### ISSUE TITLE
FSEventStreamStart error

### ISSUE THREAD

**Issue by chrishough** [guard/guard#631]
I just started getting this error when running guard on my rails 4 application on osx. Thoughts?

The error message:

```
2014-09-30 22:53 fsevent_watch[75961] (CarbonCore.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-21)
Guards jobs done. Sleeping...
22:53:38 - INFO - Browser connected.
```

Gemfile:

```
  gem 'guard', github: 'guard'
  gem 'guard-livereload'
  gem 'guard-rake'
  gem 'rack-livereload'
```

Guardfile:

```
guard 'livereload' do
  watch(%r{app/views/.+\.(erb|slim)$})
  watch(%r{app/helpers/.+\.rb})
  watch(%r{public/.+\.(css|js|html)})
  watch(%r{config/locales/.+\.yml})
  # Rails Assets Pipeline
  watch(%r{(app|vendor)(/assets/\w+/(.+\.(css|js|html))).*}) { |m| "/assets/#{m[3]}" }
  watch(%r{(app|vendor)(/assets/\w+/.+)\.s(c|a)ss}) { |m| "#{m[2]}.css" }
end

# guard 'rake', task: 'huedio:test:jshint' do
#   watch(%r{(app|vendor)(/assets/\w+/(.+\.(css|js|html))).*}) { |m| "/assets/#{m[3]}" }
# end
```

**Comment by obromios** [comment]
I have a similar issue, and it seems to be related to the number of files being watched. I have asked a stackoverflow [question](http://stackoverflow.com/questions/29343324/guard-triggering-intermittently) but have not received an answer.

**Comment by chrishough** [comment]
@obromios awesome.

**Comment by andessen** [comment]
Is there a resolution to this? I'm seeing the same problem.

**Comment by e2** [comment]
@andessen - you should probably report it here: https://github.com/thibaudgg/rb-fsevent

I don't have a clue (I don't use OSX) and it's not the right place for this issue because:

- `Guard` is for setting up rules and action to any file changes
- `Listen` is for actually listening to file change events
- `rb-fsevent` is the "driver" that handles the OSX specific stuff (that's why you should ask here: https://github.com/thibaudgg/rb-fsevent/issues/54)

**Comment by andessen** [comment]
Sounds good.
