### ISSUE TITLE
Guard Doesn't Work Properly with Growl

### ISSUE THREAD

**Issue by slavapavlutin** [guard/guard#718]
There's a `NoMethodError` when using Guard with Growl as a notifier.

When I use Ruby 2.1.2 and Guard 2.11.1 the following error message occurs:

```
04:19:16 - ERROR - Guard::RSpec failed to achieve its <run_all>, exception was:
> [#2AC23B0B7F95] NoMethodError: undefined method `type=' for #<Growl::Base:0x007fb9c17d7008>
> [#2AC23B0B7F95] /Users/slava/.rvm/gems/ruby-2.1.2/gems/growl-1.0.3/lib/growl/growl.rb:132:in `block in initialize'
> [#2AC23B0B7F95] /Users/slava/.rvm/gems/ruby-2.1.2/gems/growl-1.0.3/lib/growl/growl.rb:131:in `each'
> [#2AC23B0B7F95] /Users/slava/.rvm/gems/ruby-2.1.2/gems/growl-1.0.3/lib/growl/growl.rb:131:in `initialize'
> [#2AC23B0B7F95] /Users/slava/.rvm/gems/ruby-2.1.2/gems/growl-1.0.3/lib/growl/growl.rb:77:in `new'
> [#2AC23B0B7F95] /Users/slava/.rvm/gems/ruby-2.1.2/gems/growl-1.0.3/lib/growl/growl.rb:77:in `new'
> [#2AC23B0B7F95] /Users/slava/.rvm/gems/ruby-2.1.2/gems/growl-1.0.3/lib/growl/growl.rb:34:in `notify'
> [#2AC23B0B7F95] /Users/slava/.rvm/gems/ruby-2.1.2/gems/notiffany-0.0.2/lib/notiffany/notifier/growl.rb:77:in `_perform_notify'
> [#2AC23B0B7F95] /Users/slava/.rvm/gems/ruby-2.1.2/gems/notiffany-0.0.2/lib/notiffany/notifier/base.rb:71:in `notify'
> [#2AC23B0B7F95] /Users/slava/.rvm/gems/ruby-2.1.2/gems/notiffany-0.0.2/lib/notiffany/notifier.rb:183:in `block in notify'
> [#2AC23B0B7F95] /Users/slava/.rvm/gems/ruby-2.1.2/gems/notiffany-0.0.2/lib/notiffany/notifier.rb:182:in `each'
> [#2AC23B0B7F95] /Users/slava/.rvm/gems/ruby-2.1.2/gems/notiffany-0.0.2/lib/notiffany/notifier.rb:182:in `notify'
> [#2AC23B0B7F95] /Users/slava/.rvm/gems/ruby-2.1.2/gems/guard-2.11.1/lib/guard/notifier.rb:33:in `notify'
...
```

I guess the root of the problem is in this code of the `growl` gem:

```ruby
# line 122 of growl.rb
    def initialize options = {}, &block
      @args = []
      if block_given?
        if block.arity > 0
          yield self
        else
          self.instance_eval &block
        end
      else
        options.each do |key, value|
         # Presumably, the `type` option is being invoked as a method here causing the error
          send :"#{key}=", value 
        end
      end
    end
```

I don't know what piece of code has to be changed in order to solve the problem if it is an actual bug and not my lack of knowledge.

**Comment by e2** [comment]
Yeah, I broke it when I extracted notification to a separate gem (the repository history seems borked, so blame won't help much).

I don't have OSX, so I can't really test this.

First, the problem is in the https://github.com/guard/notiffany gem, right here: https://github.com/guard/notiffany/blob/v0.0.2/lib/notiffany/notifier/growl.rb#L77

I made it so users can pass arbitrary options to plugins, without Guard notifiers (now Notiffany notifiers) having to "know" which options are valid or not.

The fix should be to just add:

```ruby
opts.delete(:type);
```

(and delete any other options Growl doesn't understand - but ideally there should be a whitelist of acceptable options - but I don't think notiffany should be doing that).

You can create a PR in Notiffany for this, or create a PR in the Growl gem (it should ignore options it doesn't understand). Or, you can do both (Growl shouldn't crash on unknown option - I think).

I could quickly patch Notiffany myself (and add a unit test), except I can't test this - so if you can get it working and send a PR, I'll merge and release.

Let me know if you need anything.

**Comment by e2** [comment]
Let me know if the following solves the problem:

```ruby
def _perform_notify(message, opts = {})
  opts = { name: "Notiffany" }.merge(opts)
  opts.select! { |k, _| Growl::Base.switches.include?(k) }
  ::Growl.notify(message, opts)
end
```

**Comment by tony-f** [comment]
I just updated to Guard 2.11.1 on OSX with Growl (and Ruby 2.1.5) and experienced the same issue as @slavapavlutin.

I replaced the ```_perform_notify()``` method in my bundle with the one @e2 suggested and triggered a guard action.  It worked.  The Growl notification was successfully sent by Guard without the error.

@e2, you should be good to apply the patch to Notiffany for this - at least for OSX Growl users.  ;)

Thank you!

**Comment by e2** [comment]
I just released Notiffany 0.0.3 with the fix. 

Let me know if there are any other issues.

Thanks for reporting and testing!

**Comment by slavapavlutin** [comment]
Thank you for your fast response. We all appreciate that. 😊

**Comment by e2** [comment]
Glad to help! Thanks for taking time to create the report - I really appreciate it!

**Comment by tony-f** [comment]
Thanks a lot!

Tony Fernandez
Touzon Technologies, Inc.
Voice - (571) 494-1760
Fax - (703) 997-1093
Email - tfernandez@touzon.com
www.touzon.com
