### ISSUE TITLE
Guard not running tests when changes are made with most recent Rails & JRuby

### ISSUE THREAD

**Issue by JohnRiv** [guard/guard#754]
I'm running jruby-1.7.19 with RVM for a new Rails 4.2.1 project. I tried setting up Guard but when I make a change to a file, nothing happens. Here are the relevant items from my Gemfile:

gem 'rails', '4.2.1'

group :development do
  gem 'web-console', '~> 2.0'
  gem 'binding_of_caller', '0.7.3.pre1'
  gem 'guard-rspec'
  gem 'guard-teaspoon', '0.8.0.5ec53fa'
  gem 'terminal-notifier-guard'
end

You can see my Guardfile & the output of `$ LISTEN_GEM_DEBUGGING=2 bundle exec guard -d` with a modification to application_controller.rb in this gist:
https://gist.github.com/JohnRiv/4a9f642eca83e54f473e

I've used Guard plenty of times in the past, I'm not sure what is going wrong in this case.

**Comment by e2** [comment]
Thanks for the output file.

The problem is here:

```
listen: final changes: {:modified=>[], :added=>["/projects/ruby/test/app/controllers/application_controller.rb", "/projects/ruby/test/app/controllers/cart_controller.rb", "/projects/ruby/test/app/controllers/demo_controller.rb", "/projects/ruby/test/app/controllers/localization_controller.rb", "/projects/ruby/test/app/controllers/styleguide_controller.rb", "/projects/ruby/test/app/controllers/concerns/.keep"], :removed=>[]}
```

Basically, Listen detected those files as "added", not "modified" (Guard plugins mostly only respond to "modified" files - so Guard did nothing here).

A few questions pop up:

* How are you modifying the files? Are you using an editor? 
* Does `touch app/controllers/application_controller.rb` work?
* Does polling mode work? `LISTEN_GEM_DEBUGGING=2 bundle exec guard -d -p`
* If you `touch` the file multiple times, does it still keep showing ":added" instead of ":modified"?

Since this is a listen related issue, you might find some ideas here: https://github.com/guard/listen/wiki/Troubleshooting

Also, is the project big or the disk slow? The following seems like a long time: 
```
INFO -- : Record.build(): 0.5510001182556152 seconds
```

At this point it could be a bug in Listen (it should build a record of the existing files, and once they are modified, it should detect them as modified, because they should be in the record already - I'll help you debug further if that ends up being the case) ... or ... it could be a known issue (listed in the Troubleshooting wiki link above), or something new/unexpected.

I'm guessing polling will work, so let me know how the other things turn out.

**Comment by Chrisell** [comment]
I have been able to replicate the issue with jruby 1.7.19 and on multiple Rails versions.
After multiple edits I am able to  get the file to be registered within the final changes:
```
I, [2015-04-16T14:06:07.680000 #16022]  INFO -- : listen: final changes: {:modified=>["/Users/<user>/src/<project>/spec/controllers/application_controller_spec.rb"], :added=>[], :removed=>[]}
```
Starting Guard with forced polling does not seem to change the outcome:
```
$ bundle exec guard -d -p
14:09:39 - DEBUG - Notiffany: gntp not available (Please add "gem 'ruby_gntp'" to your Gemfile and run your app with "bundle exec".).
14:09:39 - DEBUG - Notiffany: growl not available (Please install the 'growlnotify' executable'    ' (available by installing the 'growl' gem).).
14:09:39 - DEBUG - Notiffany: terminal_notifier not available (Please add "gem 'terminal-notifier-guard'" to your Gemfile and run your app with "bundle exec".).
14:09:39 - DEBUG - Notiffany: libnotify not available (Unsupported platform "darwin").
14:09:39 - DEBUG - Notiffany: notifysend not available (Unsupported platform "darwin").
14:09:39 - DEBUG - Notiffany: notifu not available (Unsupported platform "darwin").
14:09:39 - DEBUG - Command execution: emacsclient --eval '1'
14:09:39 - DEBUG - Notiffany: emacs not available (Emacs client failed).
14:09:39 - DEBUG - Notiffany: tmux not available (:tmux notifier is only available inside a TMux session.).
14:09:39 - DEBUG - Notiffany: file not available (No :path option given).
14:09:39 - DEBUG - Notiffany is using TerminalTitle to send notifications.
The signal USR1 is in use by the JVM and will not work correctly on this platform
14:09:39 - DEBUG - Command execution: hash stty
14:09:39 - DEBUG - Guard starts all plugins
14:09:39 - DEBUG - Hook :start_begin executed for Guard::Cucumber
14:09:39 - INFO - Running all features
Using the default profile...
0 scenarios
0 steps
0m0.000s

14:09:52 - DEBUG - Hook :start_end executed for Guard::Cucumber
14:09:52 - DEBUG - Hook :start_begin executed for Guard::RSpec
14:09:52 - INFO - Guard::RSpec is running
14:09:52 - DEBUG - Hook :start_end executed for Guard::RSpec
14:09:52 - INFO - Guard is now watching at '/Users/<user>/src/<project>'
14:09:52 - DEBUG - Start interactor
14:09:52 - DEBUG - Command execution: /bin/sh -c stty -g 2>/dev/null
[1] guard(main)>
```

I'm not sure of what some of the other output in there means but perhaps it will be of some help.

**Comment by e2** [comment]
Thanks guys - confirmed as a bug in Guard. I'll see what's going on...

**Comment by e2** [comment]
If you're in a hurry, the quick workaround is to use the '-i' option of Guard (`bundle exec guard -i`) - this disables the Pry interactive prompt (guard becomes non-interactive), but at least Guard starts responding to changes.

**Comment by Chrisell** [comment]
Yup, '-i' worked well. Thanks for the speedy response. Definitely will help us in the interim while WIP is occurring.

**Comment by e2** [comment]
The issue is here: https://github.com/pry/pry/issues/1413

@Chrisell - perhaps changing the readline library used in Pry will help?

**Comment by e2** [comment]
Sorry guys - the best I can do for now is just abort Guard with an error (and mention the '-i' option).

I consider this closed, since I believe that ultimately people don't rely on Pry *that* much while working with Guard (Pry breakpoints in code are unrelated - they should work fine).

If anyone has a clever way to work around this, I'm all ears.
