### ISSUE TITLE
Is there some way to watch directories?

### ISSUE THREAD

**Issue by winkler1** [guard/guard#758]
Setup some code that uses dir name to take action... not the files within them. 

Is there some way to trigger on dir changes? Can't seem to make it work, even with--
```
guard :shell do
  watch /./ do |m|
    m[0] + " has changed."
  end
end
```

Thanks!

**Comment by e2** [comment]
Actually, internally the Listen library *does* watch directories (except on BSD) - but changes to directories result in scanning them (for fields).

Directories aren't too useful to treat as "content" - you're better of using actual files one way or another.

In truth, since Listen tries to be as portable as possible, it *barely* even watches files properly (lots of workarounds to make that happen).

If you're curious, check out https://github.com/guard/listen - there's even a LISTEN_GEM_DEBUGGING=2 environment variable that shows the actual events happening and how they are handled.

What's your use case? Maybe there's some compromise possible. And what OS is this for?

**Comment by winkler1** [comment]
Hi-
 The usecase is unusual, I'm using directory names to specify a series of DB objects to be created. The foldername is something like "Ad,Image,Video"... the code sees the dir name, parses it, and makes an ad with an image and video. Directories work well because resulting output is written to it.

This is on OSX.

Have used Listen.to to watch for file changes, it's fantastic :)

**Comment by e2** [comment]
I try to instead at least have a file that lists the directories. 

You could try using the rb-fsevent gem directly.

**Comment by e2** [comment]
I added a feature request here: https://github.com/guard/listen/issues/313

If this is still relevant for you, you can watch that issue there - I don't think there will be changes in Guard for this, since Guard doesn't distinguish between directories and files.
