### ISSUE TITLE
guard hangs/does not return to guard prompt when running under tmux (OSX)

### ISSUE THREAD

**Issue by andrewhavens** [guard/guard#770]
I'm noticing an issue when trying to run guard under tmux. For example, I am using the guard-rspec plugin to run my rspec tests. Outside of tmux, it runs correctly and displays an OS X notification as I expect. Running under tmux, guard hangs after running the test suite (which is likely when it is trying to display a notification). When I add `notification :tmux` to the Guardfile, it works as expected, but displays notifications in tmux. However, not everyone on my team is using tmux, also I would still like to keep the OS X notifications, so it does not seem appropriate to specify that in the Guardfile.

**Comment by e2** [comment]
Run Guard with the '-d' option - which should show the exact commands used for dealing with notification (especially tmux). You can check out the guard/notiffany project (which is what Guard uses for notification), since there may be a bug in how OSX notifications are handled (I wouldn't know - I use Linux only, so I don't use Growl, etc.).

If it's hanging, you could try Ctrl-C and maybe get a stack trace to see where exactly it's stuck.

As for project vs user settings, there's a mention in the wiki here:

https://github.com/guard/guard/wiki/Guardfile-DSL---Configuring-Guard#notification

> NOTE: since notification is more of a user setting, it's best to have each team member set this in their own ~/.guard.rb file (instead of the project Guardfile).

**Comment by misham** [comment]
Been able to replicate this.  This is only an issue with tmux.  To solve this, just add the following line to the top of your `tmux.conf`:

`set -g default-command "which reattach-to-user-namespace > /dev/null && reattach-to-user-namespace -l $SHELL || $SHELL -l"`

This is from https://github.com/julienXX/terminal-notifier/issues/115

**Comment by e2** [comment]
Thanks @misham.

I'm closing this because it's more of a Notiffany issue - it would be cool if somehow this could be avoided with a patch/warning there.

(I use Linux - I don't have OSX to even test with).
