### ISSUE TITLE
Output to guard console

### ISSUE THREAD

**Issue by ITler** [guard/guard#788]
Is there a way to define trivial output in Guardfile to be printed to guard console when starting up guard? (Imagine a greeter with some basic information for user). My ruby knowledge limits me to try `puts` and `print` but these do not work.

**Comment by e2** [comment]
Guardfile uses a DSL - and it's kind of supposed to do nothing except setup internal structures and configurations.

Instead, what you probably need is an inline Guard plugin like here:

https://github.com/guard/guard/wiki/Create-a-guard#inline-guard

Put anything you want in the `start` method, and you'll have access to every Guard plugin and library that's loaded.

`Guard::UI` is used for outputting info using colors, clearing the screen, etc.

Also, since Guard uses Pry, check out Pry configuration options (`~/.pryrc` AFAIR) for configuring the interactor (prompt, etc).

**Comment by ITler** [comment]
Thank you
