### ISSUE TITLE
Using Guard without including it on the Gemfile?

### ISSUE THREAD

**Issue by mariozaizar** [guard/guard#810]
Hi, 
I'm using `guard` and `guard-minitest` gems on my rails project. At this point the Core and 1 plugin requires 10 gems to run:

- guard.gem
- guard-compat.gem
- guard-minites.gem
- listen.gem
- lumberjack.gem
- nenv.gem
- notiffany.gem
- rb-fsevent.gem
- rb-inotify.gem
- shellany.gem

Other people feel that this is too many for a single support tool, that they will ever use.. I'm considering if there is a way to run Guard without including it on the Gemfile or any way to avoid that.

I tried using binstubs without Gemfile without luck, and run it directly, but:
```
/Users/mzaizar/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/gems/bundler-1.11.2/lib/bundler/rubygems_integration.rb:304:in `block in replace_gem': guard is not part of the bundle. Add it to Gemfile. (Gem::LoadError)
	from /Users/mzaizar/.rbenv/versions/2.1.6/bin/guard:22:in `<main>'
```

Thanks!

**Comment by e2** [comment]
I wouldn't worry about the "amount of gems", because really almost no overhead (pretty much none).

A long time ago, `listen`, `nenv`, `shellany`, `notiffany`, `guard-compat` and `lumberjack` were all part of `guard`, so they were extracted for the sake of reusability and refactoring.

I'd just include it in the `Gemfile` and don't worry.

Second, guard works without a `Gemfile`, but you might have the `RUBYGEMS_GEMDEPS` environment. Or, if you're using zsh, there might be an alias.

If you're REALLY running guard without bundler, you should see: 

`Warning: you have a Gemfile, but you're not using bundler or RUBYGEMS_GEMDEPS`

So try the following:

1. `set | grep -a RUBYGEMS_GEMDEPS`

2. Try running it using bash, not zsh (because of zsh plugins that resolve through bundler)

3. Binstubs are for bundler anyway, since they're there so you can avoid typing `bundler exec` all the time.

**Comment by mariozaizar** [comment]
Thanks for the detailed explanation @e2. I'll try that.
