### ISSUE TITLE
bundle exec guard not working with jruby 9000

### ISSUE THREAD

**Issue by vliatsos** [guard/guard#819]
### Issue

When using jruby 9000, guard 2.13.0 returns `/usr/bin/env: ruby: No such file or directory`

        $ bundle exec guard init
        /usr/bin/env: ruby: No such file or directory

This happens with the following jruby version on linux.

    $ jruby -v
    jruby 9.0.4.0 (2.2.2) 2015-11-12 b9fb7aa OpenJDK 64-Bit Server VM 25.72-b15 on 1.8.0_72-internal-b15 +jit [linux-amd64]

### Repro Steps

1. Create a simple Gemfile with just two lines

        source 'http://rubygems.org'
        gem 'guard'

2. Run `bundle install`
3. Run `bundle exec guard init`

        $ bundle exec guard init
        /usr/bin/env: ruby: No such file or directory

### Workaround
This works after editing `bin/_guard_core` in the gem to use 

    #!/usr/bin/env jruby

instead of

    #!/usr/bin/env ruby

**Comment by e2** [comment]
When you're using jruby, `ruby` should be symlinked to `jruby`.

What does `which ruby` say?
What does `which jruby` say?

E.g. I use RVM, so RVM set up `ruby` as `jruby` when I switch to JRuby.

**Comment by vliatsos** [comment]
Thanks for your quick response.
Symlinking works. 
It's just that I didn't have to do that in the past (using v2.6.1 of guard).

Should that be added in the documentation somewhere, if it's not already?
> When you're using jruby, `ruby` should be symlinked to `jruby`.

**Comment by e2** [comment]
Yes, lots of logic changed to properly handle bundler/rubygems.

There is a workaround for Windows where Ruby is selected:

https://github.com/guard/guard/blob/master/bin/guard#L102

But I'm not sure if the same approach makes sense for JRuby.
The workaround is because Windows doesn't handle shebangs.

If you're starting a Ruby process within JRuby, you want JRuby for the subprocess (and not MRI), or the subprocess will use a different Ruby version, different gems (compiled extensions), etc.

So it's up to the right shell tool to properly map `ruby` to `jruby`. E.g. RVM does this, rbenv probably does this too.

If you're running JRuby built by yourself from sources, you need to setup this yourself anyway.

So it's probably a bug/error in how your JRuby is set up for work. (Any project running ruby scripts may have issues with your setup).

That's why I asked about your setup. If it's something typical, I can figure out a workaround in Guard.

If it's just because you're doing something different, then a workaround may break things for other people (who e.g. rely on shebangs for whatever reason).

**Comment by vliatsos** [comment]
My setup is a running jruby on Ubuntu Linux.
JRuby was installed using the tarball (https://s3.amazonaws.com/jruby.org/downloads/9.0.4.0/jruby-bin-9.0.4.0.tar.gz) from the jruby.org site.
At some point, a colleague had tried `rvm` but it was supporting a prerelease version of JRuby 9000 so we gave up on using it. I believe it is supported now.

`which jruby` gives `/opt/jruby/bin/jruby` which is where jruby is installed. 
`/opt/jruby/bin` is in my `PATH` env variable.

Anyway, as I told you, I followed your advice and I created a symbolic link. 

`sudo ln -s /opt/jruby/bin/jruby /opt/jruby/bin/ruby`

And now, `which ruby` gives `/opt/jruby/bin/ruby`

So `bundle guard init` works now without the edit in `_guard_core`

**Comment by e2** [comment]
Thanks, that explains it.

I think the best solution is to leave it as an error - because the user should be warned that there's a problem, since other gems/projects may also be affected.

This also prevents problems where `ruby` actually does resolve to some non-JRuby version.

I don't mind people reporting a problem. JRuby does have an interactor problem (it shows a warning though) and it doesn't handle all the default signals. So I can help troubleshoot if people have problems.

(If there are more reports like this, I'll just detect the problem and show a warning with a link).

So I'm closing this for now. (Until there are more people with problems or there's a PR).

Thanks for reporting and investigating!
