### ISSUE TITLE
Wrong react sequence

### ISSUE THREAD

**Issue by basters** [guard/guard#821]
Hi, I have a big problem with guard and I hope that you can help me with.

I have a multithreaded script that generates some files. Guard should react on creating new file and start my second script. 

All working good on my local machine, but on server I have a problem.

Ok, look: 

1) My first script create file with name **239_301.html**
2) After it my first script create file with name **success.done**

You can see the output executing command **stat**

```
stat 239_301.html 
  File: ‘239_301.html’
  Size: 1               Blocks: 8          IO Block: 4096   regular file
Device: 400021h/4194337d        Inode: 13395       Links: 1
Access: (0644/-rw-r--r--)  Uid: ( 1000/  ubuntu)   Gid: ( 1000/  ubuntu)
Access: 2016-04-06 06:14:11.286313976 +0000
Modify: 2016-04-06 06:13:06.638302593 +0000
Change: 2016-04-06 06:13:06.638302593 +0000
 Birth: -
```

and

```
stat success.done 
  File: ‘success.done’
  Size: 0               Blocks: 0          IO Block: 4096   regular empty file
Device: 400021h/4194337d        Inode: 13396       Links: 1
Access: (0644/-rw-r--r--)  Uid: ( 1000/  ubuntu)   Gid: ( 1000/  ubuntu)
Access: 2016-04-06 06:13:06.642302593 +0000
Modify: 2016-04-06 06:13:06.642302593 +0000
Change: 2016-04-06 06:13:06.642302593 +0000
 Birth: -
```

But guard responds first to file success.done! Why?

You can see that file success.done been created after 239_301.html

My gemspec now:
`guard-shell (0.7.1)
guard (2.13.0)
`

My guardfile
```
require './lib/guard/parser'

directories ['tmp/crawled_files']
guard :parser do
  watch(%r{.*})
end
```

My :parser

```
require File.expand_path('../../../config/environment', __FILE__)
require 'guard/compat/plugin'
require './lib/crawler'


module ::Guard
  class Parser < Plugin

    def run_on_additions(paths)
      ....
    end
  end
end
```

**Comment by e2** [comment]
Yes, guard wasn't designed to give files in the correct order. This may not be easy to implement, especially since the operating system may report the changes out of order.

The Listen library (which guard uses) would have to be patched to support this.

It would also have to be a non-default option, because `stat` is potentially very expensive.

If you like, you can open an issue or PR for this in https://github.com/guard/listen - and I'll be glad to answer any questions you have there.
