### ISSUE TITLE
listen gem version 3.1.0 is now ruby >= 2.2

### ISSUE THREAD

**Issue by jmoody** [guard/guard#824]
Is there any chance you would consider pushing a point release that pins listen to 3.0.9?

The ruby requirements of `guard` is ruby >= 1.9.3.  You might need to update this.

**Comment by e2** [comment]
Both Listen and Guard need an overhaul. Both are a bit tough to tackle.

I haven't gotten to Guard yet. For now, I want to improve Listen so it survives another 1-2 years without rework. Moving the Listen codebase to 2.2 was part of this.

Currently, for Guard, it's up to users to decide whether they want to pin Listen or not.

(The community needs to drop the "backward-compatibility cult" dogma and users need to learn to upgrade Ruby just like they upgrade gems).

I'm planning on making Guard 3.x based on Ruby ~> 2.3.1 and so I'll bump the version then.

(Unless there's a bug in some Ruby < 2.2 or < 2.3 - and in that case I'll bump the dependency earlier).

The most important part for me is to let users choose Ruby 2.3 and be able to start using it's features.

**Comment by e2** [comment]
However, I'm strongly considering adding a warning in Guard about using an outdated Ruby.

**Comment by e2** [comment]
Readme for Guard updated. Ruby 2.2 is required as a dependency if people want a newer version of listen.

Example (failure + workaround using rubygems):

```
$ rvm use ruby-1.9.3
Using /home/me/.rvm/gems/ruby-1.9.3-p551
$ gem list guard
*** LOCAL GEMS ***
$ gem install guard
Building native extensions.  This could take a while...
ERROR:  Error installing guard:
	listen requires Ruby version ~> 2.2.
$ gem install listen -v 3.0.6                                             
Successfully installed listen-3.0.6
1 gem installed
$ gem install guard
Successfully installed coderay-1.1.1
Successfully installed slop-3.6.0
Successfully installed method_source-0.8.2
Successfully installed pry-0.10.3
Successfully installed lumberjack-1.0.10
Successfully installed formatador-0.2.5
Successfully installed nenv-0.3.0
Successfully installed shellany-0.0.1
Successfully installed notiffany-0.0.8
Successfully installed guard-2.13.0
10 gems installed
```

If people don't want Ruby 2.2 (an unreasonable demand IMHO), they can lock their version of Listen.

Even Listen 3.0.8 doesn't de facto support Ruby 1.9.2 (which was a bug in the dependency specification). So while locking it might work, it isn't officially supported.

**Comment by e2** [comment]
Readme has been updated. Please open an issue if you want a backporting branch and/or backporting releases.

**Comment by e2** [comment]
Justification for not bumping the major number: I couldn't release Ruby workarounds for 3.x.


Example:

1. Let's say Listen is bumped to 4.x (for Ruby 2.2)
2. Bug is discovered in Ruby 2.1, triggered by e.g. an OS library in Listen 3.0.8. 
2. Since Ruby 2.1 is unsupported, this bug won't be fixed.
3. No users are expected to upgrade to 4.x to avoid Ruby bug (unreasonable, since there's no API change). Users have to suddenly upgrade to 2.2 anyway.
4. Now, Listen 3.0.9 has to explicitly detect Ruby < 2.2 and abort with a warning to prevent the bug/crash from occurring. 
5. User avoid 4.x to their demise - due to being afraid of expecting a change in the API. Also, upgrade from 3.x to 4.x isn't automatic, but they're forced to do it anyway.

This example should've been solved with a dependency bump on Ruby within the same major version. (Which is what I did here).

**Comment by e2** [comment]
Related feature request for Bundler: https://github.com/bundler/bundler-features/issues/120

**Comment by e2** [comment]
Readme update for Guard and Listen.
