### ISSUE TITLE
Can't install guard gem for ruby 2.2.2.

### ISSUE THREAD

**Issue by Antti** [guard/guard#832]
Steps to reproduce:

```bash
gem uninstall listen -a  #confirm uninstall
gem install guard
```

It fails with:
```
ERROR:  Error installing guard:
	ruby_dep requires Ruby version >= 2.2.3, ~> 2.2.
```

ruby_dep is a dependency for `listen` gem, and doesn't support ruby < `2.2.3`

**Comment by e2** [comment]
I'm on my phone, so search for related issues in the issue tracker if you
want more info. Basically, Ruby 2.2.3 (and earlier) have serious security
vulnerabilities. (see ruby-lang.org and search the archives). So do
whatever is in your power to upgrade your Ruby. It's the best action
possible.

**Comment by westonganger** [comment]
The last version that works is 3.1.1, so force that version of listen In the meantime:

```
# Gemfile

gem 'listen', '3.1.1'
```

**Comment by e2** [comment]
Thanks, @westonganger !

@Antti - For more information about what's supported, why and what other options are available: https://github.com/guard/listen/wiki/Support-for-older-versions-of-Ruby

**Comment by e2** [comment]
@Antti - in this case specifically, Listen has the same Ruby requirement, only `ruby_dep` is being attempted to install first.

See Ruby requirement here: https://rubygems.org/gems/listen

Technically, `ruby_dep` is used so that Listen can manage it's dependencies.

I marked this as "wontfix", because I don't have a compelling use case to make `ruby_dep` work on Ruby < 2.2.3 yet. Check out the `ruby_dep` README if you want to change that there: https://github.com/e2/ruby_dep#rubydep

But, even if I relax RubyDep's dependency on Ruby >= 2.2.3, Listen will still have it's own dependency, which is exactly the same.

This means I'd need a compelling use case to support Ruby < 2.2.3, and I don't have one yet. Especially for a "development tool" like Guard you'll want it working on the newer Ruby.

If you have such a case, open a new issue so I can address "just" your case specifically.

Thank you for opening the issue though!
