### ISSUE TITLE
How to rewrite file content with inline Guard, avoiding infinite loop

### ISSUE THREAD

**Issue by Frexuz** [guard/guard#856]
How can I avoid an infinite loop with this kind of code?
(Rubocop's auto-correct does re-write files, although with a `system` command I think)

```
require 'guard/compat/plugin'

module ::Guard
  class RubyHtmlSyntaxFixer < Plugin
    def run_on_modifications(paths)
      paths.each do |path|
        text = File.read(path)
        text.gsub!('replace text', 'with something cool')
        File.open(path, 'w') {|file| file.puts text }
      end
    end
  end
end

guard 'ruby_html_syntax_fixer' do
  watch(%r{app/views/.+\.(erb|haml|slim)})
end
```

**Comment by Frexuz** [comment]
Sorry, I'll post on Google Groups instead

**Comment by e2** [comment]
Probably ignoring the change once will work - because changes are queued, so there's no way to reliably use a global variable or something to ignore the step.

Basically, you want to know if the change originates from e.g. the editor or from the "replace" method.

Overall I don't think it's a good idea to modify files inside watches.

I think it's best to integrate the RuboCop rewrite directly in your editor - so that the file buffer is rewritten before saving to the disk.

Another option is to edit a special file, like 'foo-raw.rb' so that when it's modified, 'foo.rb' is generated.

**Comment by Frexuz** [comment]
How do I ignore a step?

**Comment by e2** [comment]
Sorry for the late reply.

I think the best solution is to use `Guard.pause(:pause)` before running Rubocop on the file, and then `Guard.pause(:unpause)` after it's done. That way it should resume the events.

**Comment by Frexuz** [comment]
I'm not actually running Rubocop against it, im just replacing content with File.open(...'w').
It causes an infinite loop, even with `Guard.pause`

```
module ::Guard
  class RubyHtmlSyntaxFixer < Plugin
    def run_on_modifications(paths)
      Guard.pause(:paused)
      paths.each do |path|
        # omitted .. find stuff and replace
        File.open(path, 'w') { |file| file.puts text }
      end
      Guard.pause(:unpaused)
    end
  end
end
```

**Comment by e2** [comment]
That shouldn't be happening. Can you create a small repo to reproduce this?

**Comment by Frexuz** [comment]
Here it is :)

Steps i did:
- `rails new`
- edited gemfile
- init guard
- added my inline guard and started it

save any .erb file and watch an endless loop
